services:
  tunnelsimulator:
    build:
      context: .
      dockerfile: TunnelSimulator.Docker/dockerfile
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - tunnelsimulator_network
networks:
  tunnelsimulator_network:
    driver: bridge
